security:
         basic:
               enabled: false
         user:
               name: test
               password: 1234
         oauth2:
            client: 
                  client-id: pjmall-frontend
                  client-secret: 1234